image:
  repository: gcr.io/wuway-260614/image-renderer
  command: ["yarn serve"]
ingress:
  enable: true
  tls: true
  hostName: image-renderer.api.wuway.com
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
livenessProbe:
  enabled: true
cloudSql:
  instanceConnectionName: wuway-260614:europe-west3:wuway
