apiVersion: v1
kind: Service
metadata:
  name: {{ template "image-renderer-service.fullname" . }}
  labels:
    app: {{ template "image-renderer-service.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: web
    port: {{ .Values.service.webPort }}
    targetPort: web
  selector:
    app: {{ template "image-renderer-service.fullname" . }}
